name: Dependabot Vulnerability Scan
on:
  pull_request:
    branches:
      - master

jobs:
  dependabot-scan:
    runs-on: ubuntu-latest #im dumb

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout Dependabot Script Repo
        run: |
          cd /tmp/
          git clone https://github.com/dependabot/dependabot-script

      - name: Build Dependabot image
        run: |
          cd /tmp/dependabot-script
          docker build -t "dependabot/dependabot-script" -f Dockerfile .

      - name: Run dependabot
        env:
          GITHUB_REPOSITORY: /jonnyRyan13/micro-frontend
          PACKAGE_MANAGER: docker
          GITHUB_ACCESS_TOKEN: ${{ secrets.MFE_ACCESS_TOKEN }}

        run: |
          docker run -v $PWD:/src -e PROJECT_PATH=$GITHUB_REPOSITORY -e PACKAGE_MANAGER=$PACKAGE_MANAGER -e DIRECTORY=packages -e GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN dependabot/dependabot-script

      - name: Fail the Build if Vulnerabilities Found
        run: |
          type ./dependabot/dependabot-script/output.json && \
          if [ -f ./dependabot/dependabot-script/output.json ] && \
             jq -e '.vulnerabilities | length > 0' ./dependabot/dependabot-script/output.json >/dev/null; then
            echo "Vulnerabilities found. Blocking the merge."
            exit 1
          else
            echo "No vulnerabilities found."
          fi
