name: Build and Dependabot Scan TEST

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Adjust the Node.js version as needed


      - name: Install Dependencies
        run: cd packages/container  && npm ci

      - name: Build UI Application
        run: cd packages/container && npm run build

      - name: Build Dependabot Docker Image
        run: docker build -t my-dependabot-image -f Dockerfile .
        working-directory: ./path/to/your/Dockerfile/directory

      - name: Run Dependabot Scan with Docker
        run: |
          docker run --rm -v "$(pwd):/code" -w /code my-dependabot-image \
            /bin/sh -c "gem install dependabot --no-document && \
            dependabot --version && \
            dependabot update --fail-on-high-severity --fail-on-medium-severity --fail-on-low-severity"

      - name: Check for Vulnerabilities
        id: check-vulnerabilities
        run: echo "Checking for vulnerabilities"

      - name: Fail Workflow on Vulnerabilities
        if: steps.check-vulnerabilities.outcome == 'failure'
        run: exit 1
